### ISSUE TITLE
vb30: Proxy destination folder

### ISSUE THREAD

**Issue by kontrolermpl** [bdancer/blender-for-vray#157] opened 2016-04-07 06:38 UTC
Hi,

When I copy blend file with proxy generation folder (//proxy) from example C:\folder1\folder2\proxy for example to disc D:\ , then vray search proxy with complete access path ( c:\folder1\folder2\proxy ) instead of //proxy . Of course in blender I have this path //proxy .

**Comment by kontrolermpl** [comment] 2016-06-10 08:24
bdancer, can you fix this?

**Comment by bdancer** [comment] 2016-06-10 11:58
I'm actually can't reproduce this...

**Comment by bdancer** [comment] 2016-06-10 12:07
Ok, I think I got it, fixing.

**Comment by kontrolermpl** [comment] 2016-06-10 12:08
Thank you!

**Comment by bdancer** [comment] 2016-06-10 12:15
Fixed with https://github.com/bdancer/vb30/commit/bd0cb6029216ea057627885c46ab4b8f477144e4

**Closed by bdancer** 2016-06-10 12:15 UTC
