### ISSUE TITLE
Remap node issue

### ISSUE THREAD

**Issue by Zaurio** [bdancer/blender-for-vray#161] opened 2016-04-26 19:35 UTC
The modified remap node seems doesn't work as before.

**Comment by bdancer** [comment] 2016-04-26 21:31
Duplicate of https://github.com/bdancer/blender-for-vray/issues/156

**Comment by Zaurio** [comment] 2016-04-27 11:17
why duplicate? i meant, remap node doesnt work at all in 2.77 latest build

**Comment by bdancer** [comment] 2016-04-27 12:13
Because issue #156 is also about broken Remap node.

**Comment by Zaurio** [comment] 2016-04-27 12:26
oh, sorry for misunderstanding) i messed that page with another issue.

**Comment by bdancer** [comment] 2016-04-27 12:55
@Zaurio no worries, I've basically added comment about duplicate only for myself =)

**Comment by bdancer** [comment] 2016-04-27 14:02
Fixed with https://github.com/bdancer/plugins_desc/commit/45c51f4998aad1bca194b12aaab031205ca90ec7. Recreate Remap node or set "Input Max Tex" from 0.0 to 1.0.

**Closed by bdancer** 2016-04-27 14:02 UTC
